FROM debian:bookworm

RUN /bin/bash -c 'mkdir -p --mode=0755 /usr/share/keyrings && \
apt install curl -y && \
curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null && \
echo "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared bookworm main" | tee /etc/apt/sources.list.d/cloudflared.list && \
apt update && apt install cloudflared -y`

ENTRYPOINT ["executable", "param1", "param2"]